<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>添加单词</title>
<script type="text/javascript" src="http://zhl.besteee.com/js/jquery-min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
</head>
<style>
</style>
<body>
<div style="width: 100%;" >
<div >
<h1>
添加单词
</h1>
</div >
<div  >
<form enctype="multipart/form-data" action="chkaddword" method="post">
<div>单词类型<select name="typeid">
<option value="1">四级</option>
<option value="2">六级</option>
</select></div>
<div>单词内容<input type="text" name="word" ></div><br/>
<div>单词解析<input type="text" name="explain" ></div><br/>
<div>单词巧记<input type="text" name="remember" ></div><br/>
<div>单词搭配<input type="text" name="match" ></div><br/>
<input type="submit" value="提交">
</form>
</div>
<?php foreach ($this->allword as $value){?>
<div  style="width: 100%;">
<div  class="div1" >单词:<?=$value["word"];?></div>
<div  class="div2">解析:<?=$value["explain"];?></div>
<div  class="div1">类型:<?=$value["typeid"];?></div>
<div  class="div2">巧记:<?=$value["remember"];?></div>
<div  class="div2">搭配:<?=$value["match"];?></div>
<div  class="div2">操作:<a href="addexample?wid=<?=$value['id']; ?>&typeid=<?=$value['typeid']; ?>">添加例题</a>
||<a  id="chkword<?=$value["id"]?>" onclick="showexample(<?=$value["id"]; ?>)" >查看例题</a></div>
<div id="example<?=$value["id"]; ?>" style="display: none"></div>
</div><hr/>

<?php }
echo $this->page?>
</div>
<script type="text/javascript">

function showexample(wid){
	send_data={"wid":wid};
	$.post("../word/getexample",send_data,function(data,status){
		$("#chkword"+wid).attr("onclick","showp("+wid+")");
		data=eval("("+data+")");
		 str="<p>题目："+data.content+"</p>";
		str=str+"<p>A："+data.A+"</p>";
		str=str+"<p>B："+data.B+"</p>";
		str=str+"<p>C："+data.C+"</p>";
		str=str+"<p>D："+data.D+"</p>";
		str=str+"<p>解答："+data.explaination+"</p>";
		
		$("#example"+wid).append(str);
		$("#example"+wid).css("display","block"); 
		});
};

function showp(wid){
	dis=$("#example"+wid).css("display");
	//alert(dis);
	if(dis=="block"){
		$("#example"+wid).css("display","none");
		
	}else{
		$("#example"+wid).css("display","block");
		
	}
}
</script>
</body>
</html>