<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>添加单词</title>
<script type="text/javascript" src="http://zhl.besteee.com/js/jquery-min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
</head>
<style>
input{
width: 65%;
height: 30px;
font-size: 25px;
border-color: #d2d2d2;
border-bottom-left-radius: 10px;
border-bottom-right-radius: 10px;
border-top-left-radius: 10px;
border-top-right-radius: 10px;
}
</style>
<body>
<div align="center">
<h1>
单词例题
</h1>
</div>
<?php foreach ($this->res as $value){?>
<div>题目：<?=$value["content"]; ?></div>
<div>A : <?=$value["A"]; ?></div>
<div>B : <?=$value["B"]; ?></div>
<div>C : <?=$value["C"]; ?></div>
<div>D : <?=$value["D"]; ?></div>
<div id="event<?=$value["id"]; ?>" onclick="showanswer(<?=$value["id"]; ?>)">查看解答</div>
<div id="example<?=$value["id"]; ?>" style="display: none">答案：<?=$value["answer"] ?>--
解答：<?=$value["explaination"];?></div>
<br>
<hr>
<?php }?>
<div>
<p><font color="red">喜欢这些内容可以回复1跟我做朋友哦</font></p>
<p><font color="blue">有什么建议可以直接回复我哦</font></p>
</div>
</body>
<script type="text/javascript">
function showanswer(id){
	if($("#example"+id).css("display")=="block"){
		$("#event"+id).html("查看解答");
		$("#example"+id).css("display","none");
	}else{
		$("#event"+id).html("收回解答");
		$("#example"+id).css("display","block");
	}
	
}
</script>
</html>