<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>查看信息</title>
<script type="text/javascript" src="http://zhl.besteee.com/js/jquery-min.js"></script>
</head>
<body>
<div style="width: 100%;">
<h1>所有成员</h1>
<table style="border: 1px solid; width: 100%" >
<tr><td>姓名</td><td>用户名</td><td>电话</td><td>加入时间</td><td>性别</td><td>操作</td></tr>
<?php foreach ($this->res as $value){?>
<tr><td><?=$value["nickName"] ?></td><td><?=$value["UserName"] ?></td><td><?=$value["phone"] ?></td>
<td><?=gmdate("Y-m-d H:i:s",$value["ctime"]) ?></td><td><?php if($value["sex"]==1){echo "男";}else{echo "女";} ?></td><td>删除</td></tr>
<?php }?>
</table>
</div>
<script type="text/javascript">
$("td").css("border","1px solid");
</script>
</body>
</html>