<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>查看信息</title>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
</head>
<body>
<div style="width: 100%">
<h1 align="center">所有用户信息</h1>
<a href="showday?day=1">今天</a>
<table style="border: 1px solid;">
<tr><td>发送用户</td><td>内容</td><td>发送时间</td><td>操作</td></tr>
<?php foreach ($this->res as $value) {?>
<tr><td class="name" onmouseover="getname('<?=$value["FromUserName"];?>')"><?=$value["FromUserName"]; ?></td><td><?=$value["Content"]; ?></td>
<td><?=gmdate("Y-m-d H:i:s",$value["CreateTime"]) ?></td><td><a href="#">添加</a>||<a href="#">删除</a></td></tr>
<?php }?>
</table>
</div>
<script type="text/javascript">
function getname(username){
	send_data={"UserName":username};
	$.post("../member/getname",send_data,function(data,status){
		$(".name:contains('"+username+"')").attr("onmouseover","");
		if(data!=''){
			$(".name:contains('"+username+"')").html(data);
		}
		}
			);
}
</script>
</body>
</html>