<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>添加新闻</title>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
</head>
<body>
<div align="center">
<h1>
添加文章
</h1>
</div>
<div align="center">
<form enctype="multipart/form-data" action="chkaddnews" method="post">
选择推送图片<input type="file" name="file">  建议360*200
<br/>
文章标题<input type="text" name="Title">
<br/>
文章简介<input type="text" name="Description">
<br/>
<input type="submit" value="提交">
</form>
</div>
</body>
</html>