<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>添加新闻</title>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<script type="text/javascript" charset="utf-8" src="../ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="../ueditor/ueditor.all.min.js"> </script>
</head>
<body>
<div align="center">
<h1>
文章内容
</h1>
</div>
<div align="center">
<form enctype="multipart/form-data" action="chkaddnewshow" method="post">
<div><input type="hidden" name="id" value="<?php echo $this->id;?>"></div>
<div>标题<input type="text" name="Title" value="<?php echo $this->Title;?>"></div>
    <div>
<script type="text/plain" id="textContent" name="content"> </script>
    <script>
        var editor = new UE.ui.Editor();
        editor.render("textContent");
    </script>
    </div> 	
<input type="submit" value="提交">
</form>
</div>
</body>
</html>