<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>添加新闻</title>
<script type="text/javascript" src="http://zhl.besteee.com/js/jquery-min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
</head>
<style>
body{
	width: 700px;
   margin: 0 auto;
   border: 1px solid blue;
	font-family: Courier New;
}
body div{
	margin-left: 2px;
	margin-right: 2px;
}
</style>
<body>
<div align="center">
<h1>
添加文章
</h1>
</div>
<div align="center">
<form enctype="multipart/form-data" action="chkaddnews" method="post">
选择推送图片<input type="file" name="file">  建议360*200
<br/>
文章标题<input type="text" name="Title">
<br/>
文章简介<input type="text" name="Description">
<br/>
<input type="submit" value="提交">
</form>
</div>
<div align="center">
<?php foreach ($this->res as $value){?>
<div style="border: 1px solid;">
<div><a href="addnewshow?id=<?=$value['id'];?>&Title=<?=$value['Title']; ?>"><?=$value["Title"]; ?></a><br>
<div align="right" ><a href="deletenews?id=<?=$value['id'];?>" onClick="return confirm('是否删除<?=$value["Title"]; ?>');" >删除</a></div></div>
<br><hr>
<div  ><img  src="<?=$value["PicUrl"]; ?>" style="width: 360px;height: 200px;"/></div>
<br><hr>
<div align="left" style="word-wrap: break-word;"><span><?=$value["Description"]; ?></span></div>
</div><br><br>
<?php }
echo $this->page;
?>

</div>
</body>
</html>