<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
<title><?=$this->res["Title"]; ?></title>
</head>
<style>
.input{
width: 65%;
height: 30px;
font-size: 25px;
border-color: #d2d2d2;
border-bottom-left-radius: 10px;
border-bottom-right-radius: 10px;
border-top-left-radius: 10px;
border-top-right-radius: 10px;
}
.alldiv{
	width: 100%;
}
</style>
<body>
<div id="imgdiv">
</div>
<br/>
<div class="alldiv">
<?=$this->res["content"]?>
</div>


<script>
img=<?=$this->res["img"] ?>;
for(var p in img){
	$("#imgdiv").append('<div class="alldiv"><img width="100%" src="'+img[p]+'"></img></div><br/>');
}

</script>
</body>
</html>