<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>添加单词</title>
<script type="text/javascript" src="http://zhl.besteee.com/js/jquery-min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
</head>
<style>
.input{
width: 65%;
height: 30px;
font-size: 25px;
border-color: #d2d2d2;
border-bottom-left-radius: 10px;
border-bottom-right-radius: 10px;
border-top-left-radius: 10px;
border-top-right-radius: 10px;
}

.text{
	width: 798px;
    height: 216px;
}
</style>
<body>
<div align="center">
<h1>
添加例题
</h1>
</div>
<div align="center">
<form enctype="multipart/form-data" action="chkaddexample" method="post">
<div>单词类型<select name="typeid">
<option value="1">四级</option>
<option value="2">六级</option>
</select></div>
<input type="hidden" name="wid" value="<?=$this->wid; ?>">
<div>例题内容<textarea class="text" rows="20" cols="15" name="content"><?=$this->res["content"]; ?></textarea></div><br/>
<div>答案    A<input class="input" type="text" name="A" value="<?=$this->res["A"]; ?>" ><input type="radio" checked="checked" name="answer" value="A"></div><br/>
<div>答案    B<input class="input" type="text" name="B" value="<?=$this->res["B"]; ?>"><input type="radio" name="answer" value="B"></div><br/>
<div>答案    C<input class="input" type="text" name="C" value="<?=$this->res["C"]; ?>" ><input type="radio" name="answer" value="C"></div><br/>
<div>答案    D<input class="input" type="text" name="D" value="<?=$this->res["D"]; ?>" ><input type="radio" name="answer" value="D"></div><br/>
<div>例题解析<textarea class="text" rows="20" cols="15" name="explaination" ><?=$this->res["explaination"]; ?></textarea></div><br/>

<div ><input type="submit" value="提交"></div>
</form>
</div>
</body>
</html>
