<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>添加单词</title>
<script type="text/javascript" src="http://zhl.besteee.com/js/jquery-min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
</head>
<style>
input{
width: 65%;
height: 30px;
font-size: 25px;
border-color: #d2d2d2;
border-bottom-left-radius: 10px;
border-bottom-right-radius: 10px;
border-top-left-radius: 10px;
border-top-right-radius: 10px;
}
</style>
<body>
<div align="center">
<h1>
添加单词
</h1>
</div>
<div align="center">
<form enctype="multipart/form-data" action="chkaddword" method="post">
<div>单词类型<select name="typeid">
<option value="1">四级</option>
<option value="2">六级</option>
</select></div>
<div>单词内容<input type="text" name="word" ></div><br/>
<div>单词解析<input type="text" name="explain" ></div><br/>
<div>单词巧记<input type="text" name="remember" ></div><br/>
<div>单词搭配<input type="text" name="match" ></div><br/>
<input type="submit" value="提交">
</form>
</div>
</body>
</html>