<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>后台登录</title>
</head>

<body>
<div align="center"><h1>管理员登录</h1></div>
<form action="chklogin" method="post">
<div align="center">
<div>用户名<input type="text" name="Username" /></div>
<div>密&nbsp;&nbsp;码<input type="password" name="pwd"/></div>
<br/>
<div><input type="submit" value="登录" /></div>
</div>
</form>

</body>
</html>