<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>查看资料</title>
<script type="text/javascript" src="http://zhl.besteee.com/js/jquery-min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
</head>
<style>
body{
	width: 700px;
   margin: 0 auto;
   border: 1px solid blue;
	font-family: Courier New;
}
body div{
	margin-left: 2px;
	margin-right: 2px;
}
</style>
<body>
<div align="center">
<h1>
查看资料
</h1>
</div>
<div align="center">
<form action="chklogin" method="post">
账号<input type="text" name="UserCode">
<br/>
密码<input type="password" name="UserPwd">
<br/>
<input type="submit" value="提交">
</form>
</div>
</body>
</html>