<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<title>跟我做朋友吧</title>
</head>
<style>
.input{
width: 65%;
height: 30px;
font-size: 25px;
border-color: #d2d2d2;
border-bottom-left-radius: 10px;
border-bottom-right-radius: 10px;
border-top-left-radius: 10px;
border-top-right-radius: 10px;
}
</style>
<body>
<div style="width: 100%">
<h1 align="center">跟我做朋友吧</h1>
<form action="chkadd">
<input type="hidden" name="UserName" id="UserName" value="<?= $this->Username; ?>" />
<label>你的名字</label><input type="text"  class="input" align="middle" name="nickName"  id="nickName"/>
<br/><br />
<label>你的电话</label><input type="text"  class="input" align="middle" name="phone"  id="phone"/>
<br/><br />
<label>你的性别</label><select name="sex">
<option value="1">男</option>
<option value="2">女</option>
</select><br/><br />
<input type="submit" value="提交" />
</form>
</div>
</body>
</html>